const getters = {
    PLATFORM: 'platform',
    IS_LOGIN: 'isLogin',
    USER_INFO: 'userInfo',
    SHOW_SEARCH_VIEW: 'showSearchView',
    SEARCH_KEYWORD: 'searchKeyword',
    SHOW_PLAY_LIST: 'showPlayList',
    IS_PLAYING: 'isPlaying',
    ID: "id",
    URL: 'url',
    SONG_URL: 'songUrl',
    SONG: 'song',
    PLAY_LIST: 'playList',
    VOLUME: 'volume',
    LOOP_TYPE: 'loopType',
    IS_PAUSE: 'isPause',
    MUTED: 'muted',
    CURRENT_TIME: 'currentTime',
    DURATION: 'duration',
    SLIDER_INPUT: 'sliderInput',
    ENDED: 'ended',
    SLIDER_TIME: 'sliderTime',
    WINDOW_HEIGHT: 'windowHeight',
    WINDOW_WIDTH: 'windowWidth',
    DARK_THEME: 'darkTheme',
    WINDOW_IS_MAX: 'windowIsMax',
    FADE_VOLUME: 'fadeVolume',
    FADE_IN_FLAG: 'fadeInFlag',
    FADE_OUT_FLAG: 'fadeOutFlag',
    RECORD_VOLUME: 'recordVolume',
    SHOW_LYRICS_DETAIL: 'showLyricsDetail',
    LYRIC: 'lyric',
    FULL_SCREEN: 'fullScreen',
    ASIDE_WIDTH: 'asideWidth',
    HEADER_HEIGHT: 'headerHeight',
    SCROLL_TOP: 'scrollTop',
    PRIVILEGES: 'privileges'
}

module.exports = getters